### ISSUE TITLE
Sarif report not processed

### ISSUE THREAD

**Issue by grzesuav** [erzz/dockle-action#18]
I see my report was not processed : 
```shell
Waiting for processing to finish
  Analysis upload status is pending.
  Analysis upload status is failed.
  Error: Code Scanning could not process the submitted SARIF file:
  locationFromSarifResult: expected at least one location,locationFromSarifResult: expected at least one location,
  Error: Code Scanning could not process the submitted SARIF file:
  locationFromSarifResult: expected at least one location,locationFromSarifResult: expected at least one location,
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:334:[19](https://github.com/metacontroller/metacontroller/actions/runs/3056690261/jobs/4931107049#step:7:21))
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:60:13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:75:9)
```

report 
```json
{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0-rtm.[5](https://github.com/metacontroller/metacontroller/actions/runs/3056690261/jobs/4931107049#step:6:6).json",
  "runs": [
    {
      "tool": {
        "driver": {
          "informationUri": "https://github.com/goodwithtech/dockle",
          "name": "Dockle",
          "rules": [
            {
              "id": "CIS-DI-0005",
              "shortDescription": {
                "text": "Enable Content trust for Docker"
              },
              "helpUri": "https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#CIS-DI-0005"
            },
            {
              "id": "CIS-DI-000[6](https://github.com/metacontroller/metacontroller/actions/runs/3056690261/jobs/4931107049#step:6:7)",
              "shortDescription": {
                "text": "Add HEALTHCHECK instruction to the container image"
              },
              "helpUri": "https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#CIS-DI-0006"
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "CIS-DI-0005",
          "ruleIndex": 0,
          "level": "note",
          "message": {
            "text": "export DOCKER_CONTENT_TRUST=1 before docker pull/build"
          }
        },
        {
          "ruleId": "CIS-DI-0006",
          "ruleIndex": 1,
          "level": "note",
          "message": {
            "text": "not found HEALTHCHECK statement"
          }
        }
      ]
    }
  ]
}
```

I suspect it expects some `location` for each element

**Comment by erzz** [comment]
Hi @grzesuav 

Sorry this got ignored - too many notifications every day and I don't need to do much with this repo and thus don't check in so regularly

Would be interested to know if this is still an issue for you? and across more recent dockle versions?

I doubt its something I can directly impact without some hacking in this action as its Dockle itself that produces the report. But if still struggling I can test it out and do some digging on your behalf.

**Comment by grzesuav** [comment]
hi, it works now, seems it got fixed in new dockle version ! Closing
